baseURL = 'https://solderneer.me/'
languageCode = 'en-us'
title = "solderneer.eth"
theme = 'main'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Params

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "powered by equal parts coffee and optimism // building systems to help people live healthier [@hea_care](https://hea.care/) ✨ // also [@developer_dao](https://www.developerdao.com/) and [@ucl](https://www.ucl.ac.uk/)"

# Social tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/solderneer/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/solderneer/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
