name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
    
      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          config_order: base.header, isocalendar, languages, topics

      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics.personal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 200         # Use 200 events to compute habits
          plugin_habits_days: 14          # Keep only events from last 14 days
          plugin_habits_facts: yes        # Display facts section
          plugin_habits_charts: yes       # Display charts section
          plugin_habits_trim: yes         # Trim unused hours on daily chart
          config_timezone: Asia/Singapore # Set timezone
          plugin_music: yes
          plugin_music_limit: 4                   # Limit to 4 entries
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7asVxeuHTrAx8LrxLTSrvf # Use extracted playlist link
                                                  #   (plugin_music_provider and plugin_music_mode will be set automatically)
          config_order: habits, music
