name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
      
      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================
      
      # Terminal template example
      - name: 📙 Terminal template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
      
      # ======================================================================================
      # 🧩 PLUGINS
      # ======================================================================================

      # ======================================================================================
      # 🏆 Achievements

      # Achievements
      - name: 🏆 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, developer, contributor, octonaut
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
      
       # ======================================================================================
      # 💡 Coding habits

      # Display coding habits and recent activity (setup timezone for accurate metrics)
      - name: 💡 Habits plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_timezone: Asia/Singapore
          output_action: pull-request
          delay: 120
  
      # ======================================================================================
      # 📅 Isometric commit calendar

      # Display isometric calendar (180 days)
      - name: 📅 Isocalendar plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
      
      # Display most used languages (with some unwanted languages ignored)
      - name: 🈷️ Languages plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 4
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
      
      # ======================================================================================
      # 🐤 Latest tweets

      # Display your latest tweets (token required)
      # Don't forget to update your GitHub profile with your twitter username
      - name: 🐤 Tweets plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.tweets.svg
          token: NOT_NEEDED
          user: botlighter
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: github
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120



